name: DevTech CD

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Secrets
        run: |
          echo "VM_HOST found"
          echo "VM_USER found"
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
